export const WS_GET_MESSAGE_ALL_ORDERS = 'WS_GET_MESSAGE_ALL_ORDERS';
export const WS_CONNECTION_START_ALL_ORDERS = 'WS_CONNECTION_START_ALL_ORDERS';
export const WS_CONNECTION_SUCCESS_ALL_ORDERS = 'WS_CONNECTION_SUCCESS_ORDERS';
export const WS_CONNECTION_ERROR_ALL_ORDERS = 'WS_CONNECTION_ERROR_ORDERS';
export const WS_CONNECTION_CLOSED_ALL_ORDERS = 'WS_CONNECTION_CLOSED_ORDERS';
export const WS_SEND_MESSAGE_ALL_ORDERS = 'WS_SEND_MESSAGE_ORDERS';