export const BURGER_CONSTRUCTOR_ADD_INGRIDIENTS = 'BURGER_CONSTRUCTOR_ADD';
export const BURGER_CONSTRUCTOR_DELETE = 'BURGER_CONSTRUCTOR_DELETE';
export const BURGER_CONSTRUCTOR_ADD_BUN = 'BURGER_CONSTRUCTOR_ADD_BUN';
export const BURGER_CONSTRUCTOR_MOVE = 'BURGER_CONSTRUCTOR_MOVE';