export const WS_CONNECTION_START_ORDERS = 'WS_CONNECTION_START_ORDERS';
export const WS_CONNECTION_SUCCESS_ORDERS = 'WS_CONNECTION_SUCCESS_ORDERS';
export const WS_CONNECTION_ERROR_ORDERS = 'WS_CONNECTION_ERROR_ORDERS';
export const WS_CONNECTION_CLOSED_ORDERS = 'WS_CONNECTION_CLOSED_ORDERS';
export const WS_GET_MESSAGE_ORDERS = 'WS_GET_MESSAGE_ORDERS';
export const WS_SEND_MESSAGE_ORDERS = 'WS_SEND_MESSAGE_ORDERS';